---
- name: Install apache
  hosts: all
  become: false

  tasks:
    -  name: Checking Server Subscription
       command: subscription-manager status
       register: subscription_status
    -  name: Printing Subscription
       debug:
         msg: "{{subscription_status.stdout}}"
    -  name: Install apache and Start
       ansible.builtin.yum:
         name: httpd
         state: present
       
    -  name: Enabling Service
       service:
         state: started
         enabled: true
       when: ansible_os_family == "RedHat"
    -  name: Validating
       ansible.builtin.command: systemctl status httpd
       register: apache_status
       when: ansible_os_family == "RedHat"
    -  name: Print
       debug:
         msg: "{{ apache_status.stdout }}"
